# Mapa interativo para busca de clientes/fornecedores

Protótipo de ferramente para buscar potenciais clientes ou fornecedores com base no nincho de mercado (CNAE).

Neste projeto utilizaremos a base dados da receita federal disponível nos [dados abertos](https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj), ferramentas de geocidificação, banco de dados e ferramentas de visualização de dados geoespaciais.

## Bibliotecas utilizadas no projeto

In [1]:
import pandas as pd
import geopandas as gd
import geoalchemy2 as gsql
from geopy.geocoders import nominatim
from geopy.extra.rate_limiter import RateLimiter

## Limpeza e tratamento inicial

O volume de dados fornecido pela Receita Federal é elevado e encontra-se normalizado. Neste sentido realizaremos o tratamento "exploratório" de um dos conjuntos de dados e construiremos uma função para tratamento dos demais conjuntos de dados.

OBS: temos algumas informações relevantes sobre o arquivo que são necessárias ao tratameto dos dados, são elas:
- O arquivo é do tipo CSV, logo, utilizaremos a função read_csv do pandas;
- O separador de colunas deste arquivo é ";" e indicaremos isto com o argumento "sep='; "';
- O arquivo foi construído com unicode ANSI e indicaremos isto com o argumento "encoding='ANSI";
- O arquivo não possui títulos para as colunas e precisamos especificar esta informação pare evitar a "promoção" da primeira linha como título da coluna, para isto utilizaremos o argumento "header=None";
- Passaremos a lista de titulos "titulos_colum" para o argumento "names=" que fará a atribuição dos títulos ao dataframe.

Dadas as observações criamos duas variáveis para armazenar o caminho do arquivo e títulos das colunas

In [2]:
#caminho do arquivo
caminho_dados = "dados_brutos/estab-00.csv"

In [3]:


#Nome das colunas para reatribuição
titulos_colum = [
    "cnpj_basico",
    "cnpj_ordem",
    "cnjp_dv",
    "identificador_matriz",
    "nome_fantasia",
    "situacao_cadastral",
    "data_situacao",
    "motivo_situacao",
    "nome_cidade_exterior",
    "pais",
    "data_inicio_atv",
    "CNAE_principal",
    "CNAE_secundario",
    "tipo_logradouro",
    "logradouro",
    "numero_logra",
    "complemento",
    "bairro",
    "CEP",
    "UF",
    "municipio",
    "ddd1","telefone1",
    "ddd2","telefone2",
    "ddd_fax",'fax',
    "email",
    "situacao_especial",
    "data_situacao_especial"
]

Após a construção das variáveis de apoio realizaremos a carga dos dados com seus devidos cuidados(separador, codificação,título).

In [5]:
#carga dos dados
df_RF_01 = pd.read_csv(caminho_dados,sep=';',encoding='ANSI', header=None,names=titulos_colum)

C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\3529961736.py:2: DtypeWarning: Columns (8,21,22,23,24,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_RF_01 = pd.read_csv(caminho_dados,sep=';',encoding='ANSI', header=None,names=titulos_colum)

Nosso objetivo é listar apenas as empresas em situação ativa, neste sentido raelizaremos um filtro na coluna "situacao_cadastral" para todos os correspondentes ao valor "2" que conforme dicionário de dados corresponde as empresas ativas.

In [6]:
#filtro de cnpj's ativos
df_RF_ativos = df_RF_01[df_RF_01['situacao_cadastral']==2 ]
df_RF_ativos.head(2)

#filtro de cnpj's da região nordeste
nordeste = ['AL', 'BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE']
df_RF_ativos = df_RF_ativos[df_RF_ativos['UF'].isin(nordeste)]

Faremos a remoção das colunas não interessantes ao nosso objetivo

In [7]:
#lista de colunas para remoção
colum_drop = ['situacao_cadastral','data_situacao','motivo_situacao','nome_cidade_exterior','pais','situacao_especial','data_situacao_especial']
#drop de colunas
df_RF_ativos = df_RF_ativos.drop(colum_drop, axis=1)

De modo preliminar, guardaremos os resultados em arquivos do tipo csv para melhor instrução posterior.

In [8]:
df_RF_ativos.to_csv("Dados_pe/tratado_estab-00-NE.csv",sep=';',index=False, encoding='ANSI')

### Funçao para limpeza dos dados

Como visto o processo de limepeza ocorreu conforme o desejado e neste ponto criaremos uma função que realize o processamento dos demais arquivos

In [17]:
def pre_limpeza(arquivo ,caminho_carga ,destino_salvamento):

    #variais base
    #mascara de títulos
    titulos_colum = ["cnpj_basico","cnpj_ordem","cnjp_dv","identificador_matriz","nome_fantasia","situacao_cadastral","data_situacao","motivo_situacao",
    "nome_cidade_exterior","pais","data_inicio_atv","CNAE_principal","CNAE_secundario","tipo_logradouro","logradouro","numero_logra","complemento","bairro",
    "CEP","UF","municipio","ddd1","telefone1","ddd2","telefone2","ddd_fax",'fax',"email","situacao_especial","data_situacao_especial"]

    #colunas de descarte
    colum_drop = ['situacao_cadastral','data_situacao','motivo_situacao','nome_cidade_exterior','pais','situacao_especial','data_situacao_especial']

    #carga dos dados e adição de títulos as colunas
    df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)

    #filtro de cnpj's ativos
    df_ativos = df_carga[df_carga['situacao_cadastral']==2 ]

    #Filtro de cnpj's do nordeste
    nordeste = ['AL', 'BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE']
    df_ativos = df_ativos[df_ativos['UF'].isin(nordeste)]

    #Remoção de colunas não necessárias as análise
    df_final = df_ativos.drop(colum_drop, axis=1)

    #salvar arquivo em formato csv no destino designado com nome do arquivo acrescido por sulfixo
    df_final.to_csv(f'{destino_salvamento}/tratado_NE_{arquivo}',sep= ';',encoding= 'ANSI',index= False)

    #Função de saída meramente informativa
    return(f"arquivo limpo e salvo tratado_{arquivo}.csv")

Criada a função, criaremos variáveis auxiliáres e um laço de repetição para efetuar o tratamento dos demais arquivos brutos da Receita Federa.

In [10]:
#variáveis auxiliares a serem utilizadas

#Local do arquivo
caminho_dado = "dados_brutos"

#Lista de nomes dos arquivos 'estab-00.csv',
arquivos_list = [
    'estab-01.csv',
    'estab-02.csv', 'estab-03.csv',
    'estab-04.csv', 'estab-05.csv',
    'estab-06.csv', 'estab-07.csv',
    'estab-08.csv', 'estab-09.csv'
]

#Caminho de destino para os dados tratados
caminho_dado_limpo = 'Dados_pe'

In [18]:
#laço de repetição para coletar e processamento dos dados
for i in range(9):
    pre_limpeza(arquivos_list[i],caminho_dado,caminho_dado_limpo)

C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,18,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (1,8,22,24,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (8,21,22,24,25,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)
C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_668\1847779599.py:13: DtypeWarning: Columns (21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carga = pd.read_csv(f'{caminho_carga}/{arquivo}',sep=';',encoding='ANSI', header=None,names=titulos_colum)

## Geocodificação dos endereços

Com a redução dos dados faremos o processo de geocodificação dos endereços afim de termos um geodataframe, neste processo não trataremos os erros ou excessões. Será necessário o ajuste dos dados para melhor servir os parâmetros de buscos do motor de geocodificação.

Seguindo o processo do último exemplo, faremos um primeiro processo passo-a-passo e logo após faremos uma função para rodar execução de todos dados vigentes.

#### Passo 01 - ajuste dos dados para geocodificação

Utilizaremos a bliblioteca Nominatim, logo, precisamos passar o endereço da empresa como um valor único e que será utilizado na determinação as coordenadas, também faremos o ajuste do CNPJ para uma visualização clara.

In [6]:
#Carga do dado de geocodificação de "exemplo"
df_geocode = pd.read_csv("Dados_pe/estab_0.csv", sep=';', encoding='ANSI')
df_geocode.head(2)

C:\Users\humberto.araujo\AppData\Local\Temp\ipykernel_12784\2889796288.py:2: DtypeWarning: Columns (16,17,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_geocode = pd.read_csv("Dados_pe/estab_0.csv", sep=';', encoding='ANSI')

,cnpj_basico,cnpj_ordem,cnjp_dv,identificador_matriz,nome_fantasia,data_inicio_atv,CNAE_principal,CNAE_secundario,tipo_logradouro,logradouro,...,CEP,UF,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,59160166,1,18,1,NaN,20250129,5912099,4785799,RUA,CAROLINA SUCUPIRA,...,60140120.0,CE,1389,85.0,88717829.0,NaN,NaN,NaN,NaN,MARCELA_SHADY@HOTMAIL.COM
1,59160177,1,6,1,NaN,20250129,1622699,4330402,3A RUA,RIO PIRATININGA,...,38800000.0,MG,5241,37.0,34262407.0,NaN,NaN,NaN,NaN,CONTABILIDADEMORAES5@GMAIL.COM

Com o dataframe carregado, criaremos uma nova coluna para armazenar o endereço completo que será repassado na geocodificação. Como trata-se de uma informação "secundária" faremos a remoção das colunas com informações de endereço.

In [ ]:
#Criando nova coluna de endereço único
df_geocode['endereco'] = (

    df_geocode['tipo_logradouro']+ ' ' + df_geocode['logradouro'] +
    ', n° ' + df_geocode['numero_logra'].astype(str) + ',' + df_geocode['bairro']+
    ', UF '+ df_geocode['UF'] + ', CEP: '+ df_geocode['CEP'].astype(str)
    )
df_geocode.head(2)

,cnpj_basico,cnpj_ordem,cnjp_dv,identificador_matriz,nome_fantasia,data_inicio_atv,CNAE_principal,CNAE_secundario,tipo_logradouro,logradouro,...,UF,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email,endereco
0,59160166,1,18,1,NaN,20250129,5912099,4785799,RUA,CAROLINA SUCUPIRA,...,CE,1389,85.0,88717829.0,NaN,NaN,NaN,NaN,MARCELA_SHADY@HOTMAIL.COM,"RUA CAROLINA SUCUPIRA, n° 389,ALDEOTA, UF CE, ..."
1,59160177,1,6,1,NaN,20250129,1622699,4330402,3A RUA,RIO PIRATININGA,...,MG,5241,37.0,34262407.0,NaN,NaN,NaN,NaN,CONTABILIDADEMORAES5@GMAIL.COM,"3A RUA RIO PIRATININGA, n° 18,JARDIM SOL NASCE..."

In [ ]:
#Removendo demais colunas com dados de endereço
df_geocode = df_geocode.drop(
    ['tipo_logradouro','logradouro','numero_logra','complemento',
    'bairro','CEP','municipio'
    ], axis=1)

KeyError: "['tipo_logradouro', 'logradouro', 'numero_logra', 'complemento', 'bairro', 'CEP', 'municipio'] not found in axis"

In [12]:
df_geocode.head(2)

,cnpj_basico,cnpj_ordem,cnjp_dv,identificador_matriz,nome_fantasia,data_inicio_atv,CNAE_principal,CNAE_secundario,UF,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email,endereco
0,59160166,1,18,1,NaN,20250129,5912099,4785799,CE,85.0,88717829.0,NaN,NaN,NaN,NaN,MARCELA_SHADY@HOTMAIL.COM,"RUA CAROLINA SUCUPIRA, n° 389,ALDEOTA, UF CE, ..."
1,59160177,1,6,1,NaN,20250129,1622699,4330402,MG,37.0,34262407.0,NaN,NaN,NaN,NaN,CONTABILIDADEMORAES5@GMAIL.COM,"3A RUA RIO PIRATININGA, n° 18,JARDIM SOL NASCE..."

Com os dados ajustados, partiremos a construção da função de geocodificação. Como utilizaremos o motod o OSM, precisamos nos atentar ao intervado de requisição de no mínimo 1s.

## 2 Alocando os dados em bancos

Com o banco criado e a tabela operando vamos carregar os dados do dataframe no spatialite usando a lib sqlalchemy

Após alguns bons minutos de espera, faremos uma nova função para realizar a junção dos arquivos e posterior geocodificação.

In [ ]:
def junta_df(lista_df):